# Generated by Django 3.1.2 on 2020-10-20 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201020_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityperiod',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods1', to='api.user'),
            preserve_default=False,
        ),
    ]
