# Generated by Django 3.1.2 on 2020-10-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201020_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateTimeField(verbose_name=['%M %d %Y %I:%H %p']),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.DateTimeField(verbose_name=['%M %d %Y %I:%H %p']),
        ),
    ]
